// ─── SHARED HELPERS ──────────────────────────────────────────────────────────
const RED = "#EF4444";
const DARK = "#111111";
const GRAY = "#555555";
const LIGHT_GRAY = "#F4F4F4";
const W = 595.28; // A4 width in points
const MARGIN = 50;
const CONTENT_W = W - MARGIN * 2;

const drawHeader = (doc, title, subtitle) => {
  // Red top bar
  doc.rect(0, 0, W, 60).fill(DARK);
  doc.fill("white").font("Helvetica-Bold").fontSize(18).text("ekssesORG", MARGIN, 15, { continued: true });
  doc.fill(RED).font("Helvetica").fontSize(10).text("  AGENCY MANAGEMENT SYSTEM", { baseline: "middle" });
  doc.fill("white").font("Helvetica").fontSize(8).text(new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }), MARGIN, 42);
  doc.fill("#999999").font("Helvetica").fontSize(8).text("CONFIDENTIAL DOCUMENT", MARGIN, 42, { align: "right", width: CONTENT_W });

  // Title block
  doc.rect(0, 60, W, 40).fill(RED);
  doc.fill("white").font("Helvetica-Bold").fontSize(16).text(title, MARGIN, 72, { width: CONTENT_W * 0.7 });
  if (subtitle) doc.fill("white").font("Helvetica").fontSize(8.5).text(subtitle, MARGIN + CONTENT_W * 0.7, 76, { width: CONTENT_W * 0.3, align: "right" });

  doc.y = 115;
  doc.x = MARGIN;
};

const drawSectionHeader = (doc, label) => {
  doc.moveDown(0.3);
  const y = doc.y;
  doc.rect(MARGIN, y, CONTENT_W, 18).fill(LIGHT_GRAY);
  doc.fill(DARK).font("Helvetica-Bold").fontSize(8.5).text(label.toUpperCase(), MARGIN + 10, y + 5, { width: CONTENT_W - 20 });
  doc.y = y + 24;
  doc.x = MARGIN;
};

const drawInfoRow = (doc, label, value, x = MARGIN, w = CONTENT_W) => {
  const y = doc.y;
  doc.fill(GRAY).font("Helvetica").fontSize(8).text(label, x, y, { width: w / 2 });
  doc.fill(DARK).font("Helvetica-Bold").fontSize(8.5).text(value || "—", x + w / 2, y, { width: w / 2 });
  doc.y = y + 13;
  doc.x = MARGIN;
};

const drawDivider = (doc) => {
  doc.moveDown(0.5);
  doc.moveTo(MARGIN, doc.y).lineTo(MARGIN + CONTENT_W, doc.y).strokeColor("#DDDDDD").lineWidth(0.5).stroke();
  doc.moveDown(0.5);
};

const drawMilestoneTable = (doc, milestones) => {
  if (!milestones || milestones.length === 0) {
    doc.fill(GRAY).font("Helvetica").fontSize(9).text("No payment milestones defined.", MARGIN);
    doc.moveDown();
    return;
  }
  const cols = { idx: 30, title: 140, pct: 50, amount: 90, due: 90, status: 95 };
  const y = doc.y;
  // Header row
  doc.rect(MARGIN, y, CONTENT_W, 18).fill(DARK);
  let cx = MARGIN + 6;
  doc.fill("white").font("Helvetica-Bold").fontSize(8);
  doc.text("#", cx, y + 5, { width: cols.idx }); cx += cols.idx;
  doc.text("Phase", cx, y + 5, { width: cols.title }); cx += cols.title;
  doc.text("%", cx, y + 5, { width: cols.pct }); cx += cols.pct;
  doc.text("Amount (BDT)", cx, y + 5, { width: cols.amount }); cx += cols.amount;
  doc.text("Due Date", cx, y + 5, { width: cols.due }); cx += cols.due;
  doc.text("Status", cx, y + 5, { width: cols.status });

  doc.y = y + 18;
  milestones.forEach((m, i) => {
    const ry = doc.y;
    if (i % 2 === 0) doc.rect(MARGIN, ry, CONTENT_W, 16).fill("#F9F9F9");
    let rx = MARGIN + 6;
    const isPaid = m.status === "Paid";
    doc.fill(DARK).font("Helvetica").fontSize(8);
    doc.text(`${i + 1}`, rx, ry + 4, { width: cols.idx }); rx += cols.idx;
    doc.text(m.title || "—", rx, ry + 4, { width: cols.title }); rx += cols.title;
    doc.text(`${m.percentage || 0}%`, rx, ry + 4, { width: cols.pct }); rx += cols.pct;
    doc.text(`BDT ${Number(m.amount || 0).toLocaleString()}`, rx, ry + 4, { width: cols.amount }); rx += cols.amount;
    doc.text(m.dueDate ? new Date(m.dueDate).toLocaleDateString("en-GB") : "—", rx, ry + 4, { width: cols.due }); rx += cols.due;
    doc.fill(isPaid ? "#22C55E" : RED).font("Helvetica-Bold").text(isPaid ? "[PAID]" : "PENDING", rx, ry + 4, { width: cols.status });
    doc.y = ry + 16;
    doc.x = MARGIN;
  });
  doc.moveDown(0.3);
};

const drawClause = (doc, number, title, body) => {
  doc.moveDown(0.3);
  doc.fill(DARK).font("Helvetica-Bold").fontSize(9.5).text(`${number}. ${title}`, MARGIN, doc.y);
  doc.fill(GRAY).font("Helvetica").fontSize(9).text(body, MARGIN, doc.y + 2, { width: CONTENT_W, lineGap: 3 });
  doc.moveDown(0.5);
};

const drawFooter = (doc) => {
  const y = doc.page.height - 45;
  doc.moveTo(MARGIN, y).lineTo(MARGIN + CONTENT_W, y).strokeColor("#DDDDDD").lineWidth(0.5).stroke();
  doc.fill("#AAAAAA").font("Helvetica").fontSize(7.5)
    .text("This document was generated by ekssesORG Agency Management System. All information is confidential.", MARGIN, y + 8, { width: CONTENT_W, align: "center" });
};

// ─── CONTRACT ────────────────────────────────────────────────────────────────
export const generateContract = (doc, data) => {
  const client = data.clientId || {};
  const project = data.projectId || {};
  const contractRef = `EKS-C-${Date.now().toString().slice(-6)}`;

  drawHeader(doc, "SERVICE CONTRACT", `Ref: ${contractRef}`);

  // Two-column info block
  drawSectionHeader(doc, "Contract Parties");
  const col1 = MARGIN, col2 = MARGIN + CONTENT_W / 2 + 10, colW = CONTENT_W / 2 - 10;
  const startY = doc.y;
  doc.fill(GRAY).font("Helvetica-Bold").fontSize(8).text("CLIENT", col1, startY);
  doc.y = startY + 14; doc.x = col1;
  drawInfoRow(doc, "Full Name", client.name, col1, colW);
  drawInfoRow(doc, "Company", client.company, col1, colW);
  drawInfoRow(doc, "Email", client.email, col1, colW);
  drawInfoRow(doc, "Phone", client.phone, col1, colW);

  const r2Y = startY;
  doc.y = r2Y; doc.x = col2;
  doc.fill(GRAY).font("Helvetica-Bold").fontSize(8).text("SERVICE PROVIDER", col2, r2Y);
  doc.y = r2Y + 14; doc.x = col2;
  drawInfoRow(doc, "Agency", "ekssesORG", col2, colW);
  drawInfoRow(doc, "Project Title", project.title || "—", col2, colW);
  drawInfoRow(doc, "Contract Date", new Date().toLocaleDateString("en-GB"), col2, colW);
  drawInfoRow(doc, "Max Revisions", `${data.revisionLimit || 2}`, col2, colW);

  drawSectionHeader(doc, "Lifecycle & Validity");
  const vY = doc.y;
  drawInfoRow(doc, "Contract Status", (data.status || "Draft").toUpperCase(), col1, colW);
  drawInfoRow(doc, "Effective Date", data.effectiveDate ? new Date(data.effectiveDate).toLocaleDateString("en-GB") : "Upon Signing", col1, colW);
  drawInfoRow(doc, "Expiration", data.expirationDate ? new Date(data.expirationDate).toLocaleDateString("en-GB") : "Project Completion", col2, colW);

  doc.moveDown(0.5);
  drawDivider(doc);

  // Scope
  drawSectionHeader(doc, "1. Project Scope & Deliverables");
  doc.fill(DARK).font("Helvetica").fontSize(9).text(
    data.terms || project.scopeDescription || "Standard software development scope applies. Deliverables as verbally agreed.",
    MARGIN, doc.y, { width: CONTENT_W, lineGap: 3 }
  );
  doc.moveDown(0.8);

  // Milestones
  drawSectionHeader(doc, "2. Payment Schedule");
  drawMilestoneTable(doc, project.milestones);

  // Clauses
  drawSectionHeader(doc, "3. Legal Protections");
  drawClause(doc, "3.1", "Late Payment Policy", data.latePaymentRule || "Work will be paused immediately if any payment is not received by the agreed due date. No exceptions.");
  drawClause(doc, "3.2", "Scope Protection", "Any feature, page, or functionality not explicitly defined in Section 1 above constitutes a new request and will be quoted and billed separately.");
  drawClause(doc, "3.3", "Refund Policy", "The advance/mobilization payment is strictly non-refundable once development work has commenced, regardless of circumstances.");
  drawClause(doc, "3.4", "Revision Limit", `This agreement includes a maximum of ${data.revisionLimit || 2} revision round(s). Additional revision requests will be charged at an agreed hourly/fixed rate.`);

  if (data.specialClauses) {
    drawSectionHeader(doc, "4. Project Specific Clauses");
    doc.fill(DARK).font("Helvetica").fontSize(9).text(data.specialClauses, MARGIN, doc.y, { width: CONTENT_W, lineGap: 3 });
  }

  // Signature block
  doc.moveDown();
  const sigY = doc.y + 10;
  doc.moveTo(MARGIN, sigY + 35).lineTo(MARGIN + 160, sigY + 35).strokeColor(DARK).lineWidth(0.5).stroke();
  doc.moveTo(MARGIN + CONTENT_W - 160, sigY + 35).lineTo(MARGIN + CONTENT_W, sigY + 35).strokeColor(DARK).lineWidth(0.5).stroke();
  doc.fill(DARK).font("Helvetica-Bold").fontSize(9).text("Client Signature", MARGIN, sigY + 40);
  doc.text("ekssesORG Authorized", MARGIN + CONTENT_W - 160, sigY + 40);
  doc.fill(GRAY).font("Helvetica").fontSize(8)
    .text(client.name || "Client Name", MARGIN, sigY + 52)
    .text("ekssesORG Authorized Signatory", MARGIN + CONTENT_W - 160, sigY + 52);

  drawFooter(doc);
};

// ─── INVOICE ─────────────────────────────────────────────────────────────────
export const generateInvoice = (doc, data) => {
  const client = data.projectId?.clientId || data.clientId || {};
  const project = data.projectId || {};
  const isPaid = (data.status || "").toLowerCase() === "paid";
  const invoiceRef = data.invoiceNumber || `EKS-INV-${Date.now().toString().slice(-6)}`;

  drawHeader(doc, "TAX INVOICE", `Ref: ${invoiceRef}`);

  drawSectionHeader(doc, "Billing Information");
  const col1 = MARGIN, col2 = MARGIN + CONTENT_W / 2 + 10, colW = CONTENT_W / 2 - 10;
  const startY = doc.y;

  doc.fill(GRAY).font("Helvetica-Bold").fontSize(8).text("BILLED TO", col1, startY);
  doc.y = startY + 14;
  drawInfoRow(doc, "Client Name", client.name, col1, colW);
  drawInfoRow(doc, "Company", client.company, col1, colW);
  drawInfoRow(doc, "Email", client.email, col1, colW);

  doc.y = startY; doc.x = col2;
  doc.fill(GRAY).font("Helvetica-Bold").fontSize(8).text("INVOICE DETAILS", col2, startY);
  doc.y = startY + 14;
  drawInfoRow(doc, "Invoice #", invoiceRef, col2, colW);
  drawInfoRow(doc, "Project", project.title, col2, colW);
  drawInfoRow(doc, "Issue Date", new Date().toLocaleDateString("en-GB"), col2, colW);
  const milestone = (project.milestones || []).find(m => m._id.toString() === (data.milestoneId || "").toString());
  if (milestone) {
    drawInfoRow(doc, "Billing Phase", milestone.title, col2, colW);
  }
  drawInfoRow(doc, "Status", isPaid ? "PAID" : "DUE", col2, colW);

  drawDivider(doc);

  // Amount block
  drawSectionHeader(doc, "Amount Due");
  const amtY = doc.y;
  doc.rect(MARGIN, amtY, CONTENT_W, 60).fill(isPaid ? "#F0FDF4" : "#FFF5F5");
  doc.rect(MARGIN, amtY, 4, 60).fill(isPaid ? "#22C55E" : RED);
  doc.fill(isPaid ? "#22C55E" : RED).font("Helvetica-Bold").fontSize(28)
    .text(`BDT ${Number(data.amount || 0).toLocaleString()}`, MARGIN + 20, amtY + 12, { width: CONTENT_W - 40 });
  doc.fill(GRAY).font("Helvetica").fontSize(9)
    .text(`Method: ${data.paymentMethod || "Bank Transfer"}  |  Ref: ${invoiceRef}`, MARGIN + 20, amtY + 44);
  doc.y = amtY + 72;

  if (data.description || data.notes) {
    drawSectionHeader(doc, "Item Description & Notes");
    if (data.description) doc.fill(DARK).font("Helvetica").fontSize(8.5).text(data.description, MARGIN + 10, doc.y);
    if (data.notes) doc.fill(GRAY).font("Helvetica-Oblique").fontSize(8).text(`Note: ${data.notes}`, MARGIN + 10, doc.y + 12, { width: CONTENT_W - 20 });
    doc.y += 30;
  }

  drawSectionHeader(doc, "Payment Notes");
  drawClause(doc, "→", "Late Payment", "Full payment must be received by the due date. Delays may pause active development work.");
  drawClause(doc, "→", "Transfer Details", "Please include the Invoice Number as reference when making payment. Contact us to confirm receipt.");

  drawFooter(doc);
};

// ─── RECEIPT ─────────────────────────────────────────────────────────────────
export const generateReceipt = (doc, project) => {
  const client = project.clientId || {};
  const milestones = project.milestones || [];
  const paid = milestones.filter(m => m.status === "Paid");
  const totalPaid = paid.reduce((s, m) => s + (m.paidAmount || 0), 0);
  const balance = (project.amount || 0) - totalPaid;

  drawHeader(doc, "PAYMENT RECEIPT", `Ref: EKS-R-${Date.now().toString().slice(-5)}`);

  drawSectionHeader(doc, "Transaction Details");
  const col1 = MARGIN, col2 = MARGIN + CONTENT_W / 2 + 10, colW = CONTENT_W / 2 - 10;
  const startY = doc.y;

  doc.fill(GRAY).font("Helvetica-Bold").fontSize(8).text("CLIENT", col1, startY);
  doc.y = startY + 14;
  drawInfoRow(doc, "Name", client.name, col1, colW);
  drawInfoRow(doc, "Company", client.company, col1, colW);

  doc.y = startY; doc.x = col2;
  doc.fill(GRAY).font("Helvetica-Bold").fontSize(8).text("PROJECT", col2, startY);
  doc.y = startY + 14;
  drawInfoRow(doc, "Title", project.title, col2, colW);
  drawInfoRow(doc, "Receipt Date", new Date().toLocaleDateString("en-GB"), col2, colW);

  drawDivider(doc);

  // Latest payment highlight
  if (paid.length > 0) {
    const latest = paid[paid.length - 1];
    drawSectionHeader(doc, "Latest Payment Confirmed");
    const bY = doc.y;
    doc.rect(MARGIN, bY, CONTENT_W, 64).fill("#F0FDF4");
    doc.rect(MARGIN, bY, 4, 64).fill("#22C55E");
    doc.fill("#22C55E").font("Helvetica-Bold").fontSize(26).text(`BDT ${Number(latest.paidAmount || 0).toLocaleString()}`, MARGIN + 20, bY + 10);
    doc.fill(GRAY).font("Helvetica").fontSize(9)
      .text(`Phase: ${latest.title || "Payment"}   |   Cleared: ${latest.paidDate ? new Date(latest.paidDate).toLocaleDateString("en-GB") : "Recently"}`, MARGIN + 20, bY + 46);
    doc.y = bY + 72;
  }

  // Full milestone breakdown
  drawSectionHeader(doc, "Full Payment History");
  drawMilestoneTable(doc, milestones);

  // Summary row
  const sumY = doc.y + 4;
  doc.rect(MARGIN, sumY, CONTENT_W, 36).fill(DARK);
  doc.fill("white").font("Helvetica").fontSize(9)
    .text(`Total Budget: BDT ${Number(project.amount || 0).toLocaleString()}`, MARGIN + 10, sumY + 5)
    .text(`Total Paid: BDT ${Number(totalPaid).toLocaleString()}`, MARGIN + 10, sumY + 18);
  doc.fill(balance <= 0 ? "#22C55E" : RED).font("Helvetica-Bold").fontSize(9)
    .text(balance <= 0 ? "ACCOUNT SETTLED" : `Balance: BDT ${Number(balance).toLocaleString()}`,
      MARGIN + CONTENT_W / 2, sumY + 12, { width: CONTENT_W / 2 - 10, align: "right" });
  doc.y = sumY + 42;

  drawFooter(doc);
};

// ─── FINAL SUMMARY ───────────────────────────────────────────────────────────
export const generateSummary = (doc, project) => {
  const client = project.clientId || {};
  const milestones = project.milestones || [];
  const totalPaid = milestones.reduce((s, m) => s + (m.paidAmount || 0), 0);
  const balance = (project.amount || 0) - totalPaid;
  const isClosed = balance <= 0;

  drawHeader(doc, "PROJECT COMPLETION REPORT", isClosed ? "BALANCE ZERO" : "BALANCE OUTSTANDING");

  drawSectionHeader(doc, "Project Overview");
  drawInfoRow(doc, "Project Title", project.title);
  drawInfoRow(doc, "Client Name", client.name);
  drawInfoRow(doc, "Client Company", client.company);
  drawInfoRow(doc, "Report Generated", new Date().toLocaleDateString("en-GB"));
  drawInfoRow(doc, "Project Status", project.status || "Completed");

  drawDivider(doc);

  drawSectionHeader(doc, "Financial Summary");
  const fY = doc.y;
  const boxW = CONTENT_W / 3 - 6;
  [
    { label: "Total Budget", val: `BDT ${Number(project.amount || 0).toLocaleString()}`, color: DARK },
    { label: "Total Received", val: `BDT ${Number(totalPaid).toLocaleString()}`, color: "#22C55E" },
    { label: "Balance", val: `BDT ${Number(balance > 0 ? balance : 0).toLocaleString()}`, color: isClosed ? "#22C55E" : RED },
  ].forEach((item, i) => {
    const bx = MARGIN + i * (boxW + 9);
    doc.rect(bx, fY, boxW, 54).fill("#F9F9F9");
    doc.rect(bx, fY, boxW, 4).fill(item.color);
    doc.fill(GRAY).font("Helvetica").fontSize(8).text(item.label, bx + 8, fY + 12);
    doc.fill(item.color).font("Helvetica-Bold").fontSize(16).text(item.val, bx + 8, fY + 26, { width: boxW - 16 });
  });
  doc.y = fY + 66;

  // Milestone table
  drawSectionHeader(doc, "Payment Milestone Log");
  drawMilestoneTable(doc, milestones);

  // Closure certificate
  const certY = doc.y + 10;
  doc.rect(MARGIN, certY, CONTENT_W, 56).fill(isClosed ? "#F0FDF4" : "#FFF5F5");
  doc.rect(MARGIN, certY, 4, 56).fill(isClosed ? "#22C55E" : RED);
  doc.fill(isClosed ? "#22C55E" : RED).font("Helvetica-Bold").fontSize(13)
    .text(isClosed ? "PROJECT CLOSED - ACCOUNT SETTLED" : "!!! OUTSTANDING BALANCE EXISTS !!!", MARGIN + 16, certY + 10);
  doc.fill(GRAY).font("Helvetica").fontSize(9)
    .text(isClosed
      ? "All payments have been received in full. This document serves as final confirmation of project completion."
      : "This project has an outstanding balance. Final closure cannot be issued until full payment is received.",
      MARGIN + 16, certY + 30, { width: CONTENT_W - 30 }
    );
  doc.y = certY + 66;

  drawFooter(doc);
};
